### ISSUE TITLE
saved models can't be opened

### ISSUE THREAD

**Issue by codeHorse87** [OWASP/threat-dragon-desktop#59]
**Describe the bug**
A model available created with the same version of the app available on the local file system as json can't be opened with the desktop app.
Because of the error in the screenshot section I checked the model encoding, which is utf-8 according to the OS default settings. Changing the file encoding to Latin-1 respectively Western ISO/IEC 8859-1 did not make a difference. I guess there is a incompatible decoding within the app. 

**To Reproduce**
1. Go to 'Menu Electron'
2. Click on 'Open'
3. Select a json file of a formerly saved model 
4. Nothing happens

**Expected behavior**
The app should open the model represented by the file

**Screenshots**
`› DOMException {
  stack: "Error: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.\n" +
    '    at Object.getModelPath (/Users/###/desktop/threat-dragon-desktop/app/services/threatmodellocator.js:40:26)\n' +
    '    at /Users/###/desktop/threat-dragon-desktop/app/welcome/welcome.js:34:43\n' +
    '    at /Users/###/desktop/threat-dragon-desktop/app/services/electron.js:97:17',
  INDEX_SIZE_ERR: 1,
  DOMSTRING_SIZE_ERR: 2,
  HIERARCHY_REQUEST_ERR: 3,
  WRONG_DOCUMENT_ERR: 4,
  INVALID_CHARACTER_ERR: 5,
  NO_DATA_ALLOWED_ERR: 6,
  NO_MODIFICATION_ALLOWED_ERR: 7,
  NOT_FOUND_ERR: 8,
  NOT_SUPPORTED_ERR: 9,
  INUSE_ATTRIBUTE_ERR: 10,
  INVALID_STATE_ERR: 11,
  SYNTAX_ERR: 12,
  INVALID_MODIFICATION_ERR: 13,
  NAMESPACE_ERR: 14,
  INVALID_ACCESS_ERR: 15,
  VALIDATION_ERR: 16,
  TYPE_MISMATCH_ERR: 17,
  SECURITY_ERR: 18,
  NETWORK_ERR: 19,
  ABORT_ERR: 20,
  URL_MISMATCH_ERR: 21,
  QUOTA_EXCEEDED_ERR: 22,
  TIMEOUT_ERR: 23,
  INVALID_NODE_TYPE_ERR: 24,
  DATA_CLONE_ERR: 25,
  code: 5,
  name: 'InvalidCharacterError',
  message: "Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range."
}`

**Environment:**
 - Device: laptop, tablet
 - OS: MacOS 
 - Version: 10.15.7
 - Threat Dragon version 1.3.1

**Additional context**
I blurred sensitive path information with *###* in the screenshot section

**Comment by jgadsden** [comment]
Hello @codeHorse87 - this is not the usual result from opening a previously saved file, and it could be due to an unexpected character in the json
Are you able to attach the json file so that I can try it out? I understand if you do not, as it may have private information in it

**Comment by codeHorse87** [comment]
Hi @jgadsden no worries the problem is repeatable. Find a test file here: https://github.com/codeHorse87/exchange/blob/main/new-model.json

**Comment by jgadsden** [comment]
Thanks @codeHorse87 - with my Threat Dragon Desktop version 1.3.1 running on MacOS 10.15.7  I cloned your exchange repo.

I can open the file and edit it OK. I thought it must be rogue characters in the json but it is not that ... there must be something else that is tripping up Threat Dragon. It is good that you can reproduce it, because if you are seeing it then others will also have this problem.

I am not able to reproduce this myself, so just as a check you are able to open the Sample Model from the intro page OK? I will also provide a new model to your exchange repo to see if you can open that  OK as well:

https://github.com/codeHorse87/exchange/pull/1

**Comment by codeHorse87** [comment]
I think I got to find the root cause. It's not in the model file but in the path name 
Thanks @jgadsden  ... 
1. I tested your file, and the one I've upload in the report and I was not able to reproduce the issue anymore. Binary comparison issued content equality. 
2. Because I was still able to reproduce the exception with the original file I can track it down if the file is stored in a path with German umlaut characters. One directory in the path is /ÖVB/ when trying to open a model from this or any sub-directory the exception occurs

**Comment by jgadsden** [comment]
Thankyou @codeHorse87 for tracking this down, and it now makes sense why I could not reproduce it.

Did you want to open an enhancement issue - I guess along the lines of working with other character sets for files names + directories?

**Comment by codeHorse87** [comment]
Hi @jgadsden  make sense, how should we do it? Should I edited the current issue or create a new one linking to this one?

**Comment by jgadsden** [comment]
Well, I would create a new issue so that this one stays as it is. Certainly good to link the new one over to this one as well

**Comment by jgadsden** [comment]
@codeHorse87 do you want to close this issue, now that #62 is in place?

**Comment by codeHorse87** [comment]
closing this issue because of request [#62](https://github.com/OWASP/threat-dragon-desktop/issues/62)
