### ISSUE TITLE
Wiki - Installer location link pointing to the older mike repo

### ISSUE THREAD

**Issue by Jonas624** [OWASP/threat-dragon-desktop#83]
The links to the Installer on the following wikipage

> https://github.com/OWASP/threat-dragon-desktop/wiki

Point to

> https://github.com/mike-goodwin/owasp-threat-dragon-desktop/releases

When they should point to:

> https://github.com/OWASP/threat-dragon-desktop/releases/

**Comment by jgadsden** [comment]
Many thanks for this @Jonas624 - having a look now ...

**Comment by jgadsden** [comment]
... and now fixed up.  OK to close this @Jonas624 ?

**Comment by Jonas624** [comment]
Yes - fixed now. Feel free to close. Thanks.
