### ISSUE TITLE
Wrong SHA256 of `OWASP-Threat-Dragon-1.3.1.AppImage`

### ISSUE THREAD

**Issue by skwasniak** [OWASP/threat-dragon-desktop#89]
Seems like SHA256 of `OWASP-Threat-Dragon-1.3.1.AppImage`, listed on the download side, is wrong and is the same as for OWASP-Threat-Dragon-1.3.0.AppImage`.

```
$ sha256sum OWASP-Threat-Dragon-1.3.1.AppImage 
5cc8b5e173204ff8a2b2cdc8d1660d2312a0d6ce8b5c5fb0df7bd03c4c4fa245  OWASP-Threat-Dragon-1.3.1.AppImage

$ sha256sum OWASP-Threat-Dragon-1.3.0.AppImage 
e0d99865876c70e56a8519e67a3418bc749c098d84f4bec7cbf5c9b213c13c53  OWASP-Threat-Dragon-1.3.0.AppImage
```
![image](https://user-images.githubusercontent.com/15678876/115889395-2fbc2680-a454-11eb-91b5-5509063abed8.png)
![image](https://user-images.githubusercontent.com/15678876/115889340-25019180-a454-11eb-88d9-8c7f637080ca.png)

Debian and RPM packages' SHA256 is correct.

**Comment by jgadsden** [comment]
@skwasniak thankyou for spotting this. It should be 5cc8b5e173204ff8a2b2cdc8d1660d2312a0d6ce8b5c5fb0df7bd03c4c4fa245
and I have updated the release area for the correct checksum
Could you confirm that  I got it right this time round?
Thanks again, Jon

**Comment by skwasniak** [comment]
Yes, all good now, thank you!
