### ISSUE TITLE
Save PDF doesn't work

### ISSUE THREAD

**Issue by sherbo** [OWASP/threat-dragon-desktop#94]
**Describe the bug**
"Save PDF" doesn't create a PDF & puts the program into an unusable state. The blank white screen is what happens after clicking "Save PDF" 3 times.
![Screen Shot 2021-06-29 at 12 26 10 PM](https://user-images.githubusercontent.com/1081963/123855841-342e1100-d8d5-11eb-8569-0253fbeed62d.png)
 

**Expected behavior**
I expect to be able to save the report as PDF.

**Environment**
- Version: 1.4.0
 - Platform: Desktop
 - OS: MacOS 10.15.7
 
**To Reproduce**
1. Open demo model
2. Click "Save PDF". Nothing happens!
3. Click "Save PDF". Nothing happens!
4. Click "Save PDF". The report disappears and the program is an unusable white page state.

**Any additional context, screenshots, etc**

**Comment by jgadsden** [comment]
Hello @sherbo - many thanks of raising this. I tried it out on my version 1.4 and it certainly happens as you say.

What is happening is that  the demo model has not yet been saved, so Threat Dragon does not yet know where  to store the PDF output, and wrongly just goes blank screen as you describe.

So there are two issues here : 
1. The user should be prompted for where to store the model and PDF if the file has not yet been saved
2. It should never be blank screen

The work around is to save the demo model and then print after that, but this needs to be fixed

**Comment by sherbo** [comment]
Hey @jgadsden I think this only happens for the Demo model. I was able to "Save PDF" for my own threat model.
